
-- ---------------------------------------------------------
-- Tambahan katalog akademik untuk dropdown Profil Akademik
-- ---------------------------------------------------------
INSERT IGNORE INTO `programs` (`id`, `name`, `faculty`, `created_at`, `updated_at`) VALUES
('prog-data-science', 'S1 Sains Data', 'Fakultas Informatika', NULL, NULL),
('prog-teknik-elektro', 'S1 Teknik Elektro', 'Fakultas Teknik Elektro', NULL, NULL),
('prog-manajemen', 'S1 Manajemen', 'Fakultas Ekonomi dan Bisnis', NULL, NULL),
('prog-akuntansi', 'S1 Akuntansi', 'Fakultas Ekonomi dan Bisnis', NULL, NULL),
('prog-komunikasi', 'S1 Ilmu Komunikasi', 'Fakultas Komunikasi dan Bisnis', NULL, NULL);

INSERT IGNORE INTO `courses` (`id`, `code`, `name`, `program_id`, `created_at`, `updated_at`) VALUES
('course-if-algo', 'IF1101', 'Algoritma dan Pemrograman', 'prog-informatika', NULL, NULL),
('course-if-struktur-data', 'IF1201', 'Struktur Data', 'prog-informatika', NULL, NULL),
('course-if-rpl', 'IF2202', 'Rekayasa Perangkat Lunak', 'prog-informatika', NULL, NULL),
('course-if-jarkom', 'IF2203', 'Jaringan Komputer', 'prog-informatika', NULL, NULL),
('course-if-os', 'IF2204', 'Sistem Operasi', 'prog-informatika', NULL, NULL),
('course-if-mobile', 'IF2301', 'Pemrograman Mobile', 'prog-informatika', NULL, NULL),
('course-if-security', 'IF3301', 'Keamanan Informasi', 'prog-informatika', NULL, NULL),
('course-if-ml', 'IF3303', 'Machine Learning', 'prog-informatika', NULL, NULL),
('course-if-cloud', 'IF3304', 'Cloud Computing', 'prog-informatika', NULL, NULL),
('course-if-data-mining', 'IF3305', 'Data Mining', 'prog-informatika', NULL, NULL),
('course-if-ta', 'IF4099', 'Tugas Akhir / Skripsi', 'prog-informatika', NULL, NULL),
('course-si-manajemen-proses', 'SI1101', 'Manajemen Proses Bisnis', 'prog-si', NULL, NULL),
('course-si-analisis', 'SI1201', 'Analisis dan Perancangan Sistem Informasi', 'prog-si', NULL, NULL),
('course-si-basdat', 'SI2101', 'Basis Data Sistem Informasi', 'prog-si', NULL, NULL),
('course-si-erp', 'SI2201', 'Enterprise Resource Planning', 'prog-si', NULL, NULL),
('course-si-bi', 'SI2301', 'Business Intelligence', 'prog-si', NULL, NULL),
('course-si-pm', 'SI3101', 'Manajemen Proyek Sistem Informasi', 'prog-si', NULL, NULL),
('course-si-audit', 'SI3201', 'Audit Sistem Informasi', 'prog-si', NULL, NULL),
('course-si-uiux', 'SI3301', 'User Experience dan Desain Produk Digital', 'prog-si', NULL, NULL),
('course-ds-stat', 'DS1101', 'Statistika Dasar untuk Sains Data', 'prog-data-science', NULL, NULL),
('course-ds-python', 'DS1201', 'Python untuk Analisis Data', 'prog-data-science', NULL, NULL),
('course-ds-visual', 'DS2101', 'Visualisasi Data', 'prog-data-science', NULL, NULL),
('course-ds-bigdata', 'DS2201', 'Big Data Analytics', 'prog-data-science', NULL, NULL),
('course-ds-ml', 'DS3101', 'Machine Learning untuk Sains Data', 'prog-data-science', NULL, NULL),
('course-ds-etl', 'DS3201', 'Data Warehouse dan ETL', 'prog-data-science', NULL, NULL),
('course-dkv-visual-basic', 'DKV1101', 'Dasar Desain Visual', 'prog-dkv', NULL, NULL),
('course-dkv-typo', 'DKV1201', 'Tipografi', 'prog-dkv', NULL, NULL),
('course-dkv-branding', 'DKV2201', 'Branding dan Identitas Visual', 'prog-dkv', NULL, NULL),
('course-dkv-motion', 'DKV3101', 'Motion Graphic', 'prog-dkv', NULL, NULL),
('course-dkv-ads', 'DKV3201', 'Creative Advertising', 'prog-dkv', NULL, NULL),
('course-te-rangkaian', 'TE1101', 'Rangkaian Listrik', 'prog-teknik-elektro', NULL, NULL),
('course-te-elektronika', 'TE1201', 'Elektronika Dasar', 'prog-teknik-elektro', NULL, NULL),
('course-te-sinyal', 'TE2101', 'Sinyal dan Sistem', 'prog-teknik-elektro', NULL, NULL),
('course-te-iot', 'TE3101', 'Internet of Things', 'prog-teknik-elektro', NULL, NULL),
('course-mj-marketing', 'MJ1101', 'Prinsip Manajemen dan Pemasaran', 'prog-manajemen', NULL, NULL),
('course-mj-finance', 'MJ2101', 'Manajemen Keuangan', 'prog-manajemen', NULL, NULL),
('course-mj-ops', 'MJ2201', 'Manajemen Operasi', 'prog-manajemen', NULL, NULL),
('course-mj-startup', 'MJ3101', 'Kewirausahaan dan Startup Digital', 'prog-manajemen', NULL, NULL),
('course-ak-basic', 'AK1101', 'Akuntansi Dasar', 'prog-akuntansi', NULL, NULL),
('course-ak-cost', 'AK2101', 'Akuntansi Biaya', 'prog-akuntansi', NULL, NULL),
('course-ak-audit', 'AK3101', 'Audit dan Assurance', 'prog-akuntansi', NULL, NULL),
('course-ik-public-speaking', 'IK1101', 'Public Speaking', 'prog-komunikasi', NULL, NULL),
('course-ik-pr', 'IK2101', 'Public Relations', 'prog-komunikasi', NULL, NULL),
('course-ik-digital', 'IK3101', 'Komunikasi Digital dan Media Sosial', 'prog-komunikasi', NULL, NULL);
